name: st
version: "0.1"
summary: This is a test app for using nodejs for sensortag
description: 
  This app is used to show how to read data from a sensortag
confinement: strict

apps:
  st:
    command: bin/sensortag
    # daemon: simple
    plugs: [network-bind]
  sensor:
    command: bin/wrapper
    plugs: [home,bluez]
  sh:
    command: bin/sh
  ctrl:
    command: usr/bin/bluetoothctl


parts:
  bluez:
    plugin: nil
    stage-packages:
      - bluetooth
      - bluez
      - blueman

  node:
    plugin: nodejs
    source: . 

  glue:
    plugin: copy
    files:
      ./bin: bin
